### ISSUE TITLE
http://localhost:3000/horoscope?time=1895-05-12 00:30:00 05:00&latitude=13.5503&longitude=78.50288 is error

### ISSUE THREAD

**Issue by rajna** [ryuphi/astrology-api#10]

**Comment by ryuphi** [comment]
Hi @rajna !
I recommend using the ISO8601 format (example 2020-04-16T01:06:54+05:00) and you should escape the **+ sign** to avoid problems with positive time offsets, **example +05:00 should be %2B05:00**. Maybe over the weekend or tomorrow I will fix these.

Your url can be: https://dev-astrology-api.herokuapp.com/horoscope?time=1895-05-12T00:30:00%2B05:00&latitude=13.5503&longitude=78.50288

Thanks for reporting!
