### ISSUE TITLE
Got error while installing node modules

### ISSUE THREAD

**Issue by tirumalavasu** [ryuphi/astrology-api#14]
Error: Cannot find module 'C:\Workspace\Projects\astrology-api\node_modules\swisseph\lib/../build/Release/swisseph.node'
Require stack:
- C:\Workspace\Projects\astrology-api\node_modules\swisseph\lib\swisseph.js
- C:\Workspace\Projects\astrology-api\src\astrologer\astros.js
- C:\Workspace\Projects\astrology-api\src\astrologer\index.js
- C:\Workspace\Projects\astrology-api\src\api\index.js
- C:\Workspace\Projects\astrology-api\app.js
- C:\Workspace\Projects\astrology-api\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Workspace\Projects\astrology-api\node_modules\swisseph\lib\swisseph.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Workspace\\Projects\\astrology-api\\node_modules\\swisseph\\lib\\swisseph.js',
    'C:\\Workspace\\Projects\\astrology-api\\src\\astrologer\\astros.js',
    'C:\\Workspace\\Projects\\astrology-api\\src\\astrologer\\index.js',
    'C:\\Workspace\\Projects\\astrology-api\\src\\api\\index.js',
    'C:\\Workspace\\Projects\\astrology-api\\app.js',
    'C:\\Workspace\\Projects\\astrology-api\\index.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ryuphi** [comment]
Hi! First of all, sorry for the delay. I had not tried on Windows. What version of nodejs do you have installed? I tried nodejs v14 on windows 10 and I had no problems but I found the following requirements.

* I recommend you to use nodejs version 14 onwards, at least it is with the one that I have been testing and programming. If you need support for several versions of nodejs on your machine you can use nvm but I don't know if they have support for windows.
*  You must have python installed. The reason for this is that the library used for calculations compiles the binaries in c ++ using node-gyp. You can download python from windows store.
*  The project uses node-gyp, to compile the swisseph libraries and use them as addons in nodejs. I leave you the following link with the instructions to run it on windows (You need to install some visual studio compilation tools) https://github.com/nodejs/node-gyp#on-windows.

With that, I had no problem running the project. I hope I've helped.

Thanks for reporting the problem! I need to update the requirements and maybe the installation guide when I do it and see that you have no problems I will close the issue.
