### ISSUE TITLE
Inclusion of speed property for planets in API

### ISSUE THREAD

**Issue by amitabh-srivastav** [ryuphi/astrology-api#18]
I am unable to get the speed property of planets from the package. Can someone help me on how to include it in the API, as the Speed flag is already included in the parameters.

**Comment by ryuphi** [comment]
Hi! I added in #19 the speed field in the api response along with the retrograde status field, this field shows if the astro is in retrograde phase or not. 

I hope this change can help you.

Greetings.

**Comment by amitabh-srivastav** [comment]
Thanks a lot for promptly completing the much required enhancement.
